export { default as CloseSVG } from './close.svg?inline';
export { default as InstagramSVG } from './instagram.svg?inline';
export { default as NextSVG } from './next.svg?inline';
export { default as FacebookSVG } from './facebook.svg?inline';
export { default as GoogleSVG } from './google.svg?inline';
export { default as DateSVG } from './date.svg?inline';
export { default as LocationSVG } from './location.svg?inline';
export { default as SaveSVG } from './save.svg?inline';
export { default as SavedSVG } from './saved.svg?inline';
